"use client";

import { useState, useEffect } from "react";
import { toast } from "sonner";
import { I } from "@/components/icons";
import { Chip } from "@/components/ui";
import { useUI } from "@/lib/store";
import { channelMeta, redditBody, carouselSets, tiktokScripts, type Post, type CarouselSlide } from "@/lib/data";
import { useCampaign, useApprovePost } from "@/lib/queries";

// Format families drive which actions/edit affordances the drawer shows (PRD §5.4).
type EditModel = "text" | "carousel" | "image" | "video";

function editModelFor(post: Post): EditModel {
  if (post.kind === "tiktok") return "video";
  if (post.kind === "reddit" || post.kind === "thread") return "text";
  // IG: carousels are templated text-layer edits; single photo posts get caption + image regen.
  if (post.type.toLowerCase().includes("carousel")) return "carousel";
  return "image";
}

// Non-blocking platform constraints surfaced in the drawer (PRD §7.4).
function constraintFor(post: Post): string | null {
  if (post.kind === "reddit") return "Reddit requires posting karma in some subreddits — Offload will warn if your account is below the threshold.";
  if (post.kind === "tiktok") return "Video is founder-posted in v1 — Offload never auto-publishes to TikTok. Mark it filmed to activate the slot.";
  return null;
}

export const ContentDetail = () => {
  const post = useUI((s) => s.openedPost);
  const close = useUI((s) => s.closePost);
  if (!post) return null;
  return <Drawer key={post.id} post={post} onClose={close} />;
};

const Drawer = ({ post, onClose }: { post: Post; onClose: () => void }) => {
  const { data: campaign } = useCampaign();
  const approve = useApprovePost();
  const setChatOpen = useUI((s) => s.setChatOpen);
  const meta = channelMeta[post.channel];
  const date = campaign?.dateLabels?.[post.day] ?? { num: 0, dow: "", month: "" };
  const model = editModelFor(post);
  const constraint = constraintFor(post);
  const isVideo = model === "video";

  // Escape-to-close, matching the click-outside backdrop.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const editLabel =
    model === "text" ? "Edit copy" : model === "carousel" ? "Edit text" : model === "image" ? "Edit caption" : "Edit script";

  return (
    <>
      <div className="drawer-backdrop" onClick={onClose} />
      <div className="drawer">
        <div className="drawer-head">
          <div className="cb-icon" style={{ background: meta.color, width: 32, height: 32, borderRadius: 8 }}>
            <meta.Icon size={18} />
          </div>
          <div style={{ flex: 1 }}>
            <div className="eyebrow" style={{ marginBottom: 2 }}>
              {meta.name} · {post.type}
            </div>
            <div style={{ fontSize: 14, fontWeight: 500, color: "var(--espresso)", lineHeight: 1.25 }}>{post.title}</div>
          </div>
          <button className="btn btn-ghost btn-sm" style={{ padding: 6 }} onClick={onClose} aria-label="Close">
            <I.X size={16} />
          </button>
        </div>

        <div className="drawer-body">
          {/* Meta row */}
          <div className="flex gap-3" style={{ marginBottom: 20, flexWrap: "wrap" }}>
            <Chip>
              <I.Clock size={11} /> Scheduled {date.dow}, {date.month} {date.num} · {post.time}
            </Chip>
            <Chip>
              <I.Sparkle size={11} /> Generated by Offload
            </Chip>
            {isVideo ? (
              <Chip dot="var(--warn)">
                <span style={{ marginLeft: 2 }}>Awaiting filming</span>
              </Chip>
            ) : (
              <Chip tone="teal" dot>
                <span style={{ marginLeft: 2 }}>Approved</span>
              </Chip>
            )}
          </div>

          {post.kind === "reddit" && <RedditPreview post={post} />}
          {post.kind === "carousel" && <CarouselPreview post={post} />}
          {post.kind === "tiktok" && <TikTokPreview post={post} />}
          {post.kind === "thread" && <ThreadPreview post={post} />}

          {/* Platform constraint flag */}
          {constraint && (
            <div
              style={{
                marginTop: 16,
                padding: "10px 14px",
                background: "var(--surface-2)",
                borderRadius: 8,
                fontSize: 12.5,
                color: "var(--text-muted)",
                display: "flex",
                alignItems: "flex-start",
                gap: 10,
              }}
            >
              <I.Bell size={13} style={{ marginTop: 1, flexShrink: 0, color: "var(--espresso)" }} />
              <span>{constraint}</span>
            </div>
          )}

          {/* AI rationale */}
          <div className="card" style={{ marginTop: 24, background: "var(--cream)", borderColor: "transparent" }}>
            <div className="card-head" style={{ marginBottom: 10 }}>
              <h4
                className="card-title"
                style={{ fontSize: 12, textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--text-muted)", fontWeight: 500 }}
              >
                Why Offload wrote this
              </h4>
            </div>
            <p style={{ fontSize: 13.5, color: "var(--espresso)", margin: 0, lineHeight: 1.6 }}>
              {post.kind === "reddit" &&
                "Long-form, numbers-forward founder posts perform 4.2x better than promotional posts on r/Coffee. This post leads with specifics (price, temperatures, batch sizes) to earn credibility before mentioning the brand."}
              {post.kind === "carousel" &&
                'Carousels that open with a strong one-line claim outperform question-led carousels by 38% in this niche. Slide pacing follows the "hook → tension → resolution" pattern that\'s working best on your competitor accounts.'}
              {post.kind === "tiktok" &&
                "TikTok slideshows in your category convert 2.4x better than talking-head when posted between 6–9pm. The script is written for vertical, no-voiceover delivery with strong on-screen text hooks every 4 seconds."}
              {post.kind === "thread" &&
                "Short, opinionated X posts in your voice (warm + witty, lightly contrarian) outperform threads in your niche. Offload sticks to one strong claim per post and lets the audience reply."}
            </p>
          </div>
        </div>

        <div className="drawer-foot">
          <button className="btn btn-secondary" onClick={() => setChatOpen(true)}>
            <I.Edit size={13} /> {editLabel}
          </button>
          {model === "image" && (
            <button className="btn btn-secondary" onClick={() => toast("Regenerating image from your prompt…")}>
              <I.Image size={13} /> Regenerate image
            </button>
          )}
          <button className="btn btn-secondary" onClick={() => toast("Pick a new time to reschedule.")}>
            <I.Clock size={13} /> Reschedule
          </button>
          <button
            className="btn btn-ghost"
            style={{ marginLeft: "auto", color: "var(--danger)" }}
            onClick={() => {
              toast("Post deleted.");
              onClose();
            }}
          >
            <I.Trash size={13} /> Delete
          </button>
          {isVideo ? (
            <button
              className="btn btn-primary"
              onClick={() => {
                toast.success("Marked as filmed — calendar slot activated.");
                onClose();
              }}
            >
              <I.Film size={13} /> Mark filmed
            </button>
          ) : (
            <button
              className="btn btn-primary"
              onClick={() => {
                const done = () => {
                  toast.success("Post approved — it'll publish at its scheduled time.");
                  onClose();
                };
                if (post.dbId) approve.mutate(post.dbId, { onSuccess: done, onError: () => toast.error("Couldn't approve — try again.") });
                else done();
              }}
            >
              <I.Check size={13} /> Approve
            </button>
          )}
        </div>
      </div>
    </>
  );
};

const RedditPreview = ({ post }: { post: Post }) => (
  <div className="reddit-post">
    <div className="reddit-meta">
      <div style={{ width: 18, height: 18, borderRadius: "50%", background: "var(--c-reddit)", display: "grid", placeItems: "center" }}>
        <I.Reddit size={14} style={{ color: "white" }} />
      </div>
      <span className="sub">{post.subreddit ?? "r/Coffee"}</span>
      <span>· Posted by u/brewlab_andre</span>
      <span>· {post.time}</span>
    </div>
    <h3 className="reddit-title">{post.title}</h3>
    <div
      className="reddit-body"
      dangerouslySetInnerHTML={{
        __html: (((post.content as { body?: string } | undefined)?.body || redditBody))
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;")
          .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
          .replace(/\n/g, "<br/>"),
      }}
    />
    <div className="reddit-foot">
      <span>
        <I.ArrowUp size={12} style={{ verticalAlign: "-2px", marginRight: 4 }} />1.2k
      </span>
      <span>284 comments</span>
      <span>
        <I.Repeat size={12} style={{ verticalAlign: "-2px", marginRight: 4 }} />Share
      </span>
      <span style={{ marginLeft: "auto", color: "var(--text-faint)", fontSize: 11 }}>(forecast)</span>
    </div>
  </div>
);

const CarouselPreview = ({ post }: { post: Post }) => {
  const live = post.content as { slides?: { heading: string; sub: string }[]; caption?: string } | undefined;
  const slides: CarouselSlide[] = live?.slides?.length
    ? live.slides.map((s, i) => ({
        eyebrow: "",
        text: s.heading,
        sub: s.sub || undefined,
        tone: (["espresso", "cream", "teal"] as const)[i % 3],
      }))
    : (post.slidesId && carouselSets[post.slidesId]) || carouselSets.sad_iced;
  const [active, setActive] = useState(0);
  const slide = slides[active];
  return (
    <div className="carousel-frame">
      <div className="carousel-tabs">
        {slides.map((_, i) => (
          <button
            key={i}
            className={`carousel-tab ${active === i ? "active" : ""}`}
            onClick={() => setActive(i)}
            aria-label={`Slide ${i + 1}`}
            aria-pressed={active === i}
          >
            {String(i + 1).padStart(2, "0")}
          </button>
        ))}
      </div>

      <div className={`carousel-slide tone-${slide.tone}`}>
        <span className="slide-num">
          {String(active + 1).padStart(2, "0")} / {String(slides.length).padStart(2, "0")}
        </span>
        {slide.eyebrow && <div className="slide-eyebrow">{slide.eyebrow}</div>}
        <div className="slide-text">{slide.text}</div>
        {slide.sub && (
          <div style={{ fontSize: 14, fontFamily: "var(--font-sans)", marginTop: 14, opacity: 0.7, fontStyle: "normal" }}>{slide.sub}</div>
        )}
      </div>

      <div className="flex justify-between items-center" style={{ marginTop: 14, padding: "0 4px" }}>
        <button className="btn btn-ghost btn-sm" onClick={() => setActive(Math.max(0, active - 1))} disabled={active === 0}>
          <I.ChevronLeft size={14} /> Prev
        </button>
        <span className="text-mono" style={{ fontSize: 12, color: "var(--text-muted)" }}>
          {active + 1} of {slides.length}
        </span>
        <button
          className="btn btn-ghost btn-sm"
          onClick={() => setActive(Math.min(slides.length - 1, active + 1))}
          disabled={active === slides.length - 1}
        >
          Next <I.ChevronRight size={14} />
        </button>
      </div>

      <div style={{ marginTop: 16, padding: "12px 14px", background: "var(--surface-2)", borderRadius: 8 }}>
        <div className="eyebrow" style={{ marginBottom: 6 }}>
          Caption
        </div>
        <p style={{ fontSize: 13.5, margin: 0, color: "var(--espresso)", lineHeight: 1.5, whiteSpace: "pre-wrap" }}>
          {live?.caption ||
            "Cold brew that doesn't taste like sad iced coffee. 18 hours of slow steep, 50°F, no shortcuts. 200-bottle batch — link in bio."}
        </p>
      </div>
    </div>
  );
};

const TikTokPreview = ({ post }: { post: Post }) => {
  const tc = post.content as { hook?: string; scenes?: string[]; shot_note?: string; duration_sec?: number } | undefined;
  const script =
    tc && (tc.hook || tc.scenes?.length)
      ? {
          hook: tc.hook ?? "",
          duration: tc.duration_sec ? `${tc.duration_sec}s` : "—",
          scenes: (tc.scenes ?? []).map((s) => ({ onScreen: s, vo: tc.shot_note ?? "", meta: "" })),
        }
      : (post.scriptId && tiktokScripts[post.scriptId]) || tiktokScripts.blind_taste;
  return (
    <div>
      <div className="card" style={{ background: "var(--espresso)", color: "var(--cream)", padding: 18, marginBottom: 16 }}>
        <div className="eyebrow" style={{ color: "rgba(240,244,252,0.6)", marginBottom: 6 }}>
          Hook · 0:00
        </div>
        <p style={{ fontFamily: "var(--font-serif)", fontSize: 22, lineHeight: 1.2, margin: 0, fontStyle: "italic" }}>
          &quot;{script.hook}&quot;
        </p>
        <div className="flex gap-3 mt-4 text-mono" style={{ fontSize: 11, color: "rgba(240,244,252,0.55)" }}>
          <span>{script.duration} total</span>
          <span>·</span>
          <span>{script.scenes.length} scenes</span>
          <span>·</span>
          <span>9:16 vertical</span>
        </div>
      </div>

      <div className="eyebrow" style={{ marginBottom: 8 }}>
        Scene-by-scene
      </div>
      <div className="card" style={{ padding: "4px 18px" }}>
        {script.scenes.map((s, i) => (
          <div className="tt-script-row" key={i}>
            <div className="scene-num">{i + 1}</div>
            <div className="scene-body">
              <p className="scene-onscreen">&quot;{s.onScreen}&quot;</p>
              <p className="scene-vo">{s.vo}</p>
              <div className="scene-meta">{s.meta}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

const ThreadPreview = ({ post }: { post: Post }) => {
  const tc = post.content as { tweets?: string[]; body?: string } | undefined;
  const isThread = post.format === "x_thread" || post.type.toLowerCase().includes("thread");
  const tweets =
    tc?.tweets?.length
      ? tc.tweets
      : tc?.body
        ? [tc.body]
        : isThread
          ? [
              'Most "small batch" cold brew you see on a grocery shelf is doing 4,000-bottle runs.',
              "For context: ours are 200. Both technically small batch. One of them is not.",
              "The label says nothing about how long it's been sitting on a pallet, or that 80% of the bottle is water, or that the concentrate is 6 months old.",
              "I'm not mad about it. I just think you should know what you're paying $5.99 for.",
              "If you want the actual small-batch version, it's $4.50 and you can find us in 12 cafés in Brooklyn. (Or brewlab.co, link in bio.)",
            ]
          : [post.title];

  return (
    <div className="flex flex-col gap-3">
      {tweets.map((t, i) => (
        <div key={i} className="reddit-post" style={{ padding: 16 }}>
          <div className="reddit-meta">
            <div className="avatar" style={{ width: 28, height: 28, fontSize: 11 }}>
              BL
            </div>
            <span className="sub">Brew Lab</span>
            <span>@brewlab</span>
            <span>· {post.time}</span>
          </div>
          <p style={{ fontSize: 14.5, color: "var(--text)", lineHeight: 1.5, margin: 0 }}>{t}</p>
          <div className="reddit-foot" style={{ marginTop: 12, paddingTop: 12 }}>
            <span>
              <I.Heart size={12} style={{ verticalAlign: "-2px", marginRight: 4 }} />
              {200 + ((i * 173 + 311) % 800)}
            </span>
            <span>
              <I.Repeat size={12} style={{ verticalAlign: "-2px", marginRight: 4 }} />
              {40 + ((i * 97 + 53) % 200)}
            </span>
            <span style={{ marginLeft: "auto", color: "var(--text-faint)" }}>(forecast)</span>
          </div>
          {isThread && i < tweets.length - 1 && (
            <div style={{ width: 2, height: 12, background: "var(--border-strong)", marginLeft: 13, marginTop: 4, marginBottom: -8 }} />
          )}
        </div>
      ))}
    </div>
  );
};
