import { test, expect } from "@playwright/test";
import { adminDb, countPosts } from "./helpers/db";
import { onboarding, calendar, scripts, chat, drawer } from "./helpers/selectors";

// ===== LIVE DB-state e2e =====
// Re-walks the meaningful MUTATING steps of the demo path against the real (deployed or
// local-live) app WITH the injected session from global-setup, then asserts the rows the app
// wrote actually landed via the service-role adminDb() (which bypasses RLS).
//
// Inert unless E2E_LIVE=1: the whole file top-level-skips below, so the `live` project is a no-op
// for anyone without live creds (and the `mock` project never matches it — it has its own webServer
// and storageState=undefined). Asserts use expect.poll because the writes are async (SSE generate,
// route-handler upserts, RLS round-trips), so we tolerate a little settling time.
test.skip(process.env.E2E_LIVE !== "1", "live DB e2e disabled (set E2E_LIVE=1 + creds)");

// Run serially: the campaign generated by the first test is the substrate the later tests edit /
// approve / mark-filmed. Sharing one account across tests means each step builds on the last.
test.describe.serial("live DB mutations land real rows", () => {
  let accountId: string;

  // accounts.id === auth.uid() for real users: the handle_new_user trigger inserts
  // accounts(id, email) = (new.id, new.email) on signup (supabase/migrations/0001_init.sql), and
  // lib/api.ts resolveAccount() reads the signed-in user's own rows keyed on that id. So resolving
  // the test user's account is just "find the accounts row for E2E_TEST_EMAIL".
  test.beforeAll(async () => {
    const email = process.env.E2E_TEST_EMAIL!;
    const byEmail = await adminDb().from("accounts").select("id").eq("email", email).maybeSingle();
    if (byEmail.error) throw byEmail.error;
    if (byEmail.data) {
      accountId = byEmail.data.id;
      return;
    }
    // Fallback: resolve via the auth admin API if the accounts row hasn't propagated yet.
    const { data, error } = await adminDb().auth.admin.listUsers();
    if (error) throw error;
    const user = data.users.find((u) => u.email?.toLowerCase() === email.toLowerCase());
    if (!user) throw new Error(`live-db: no auth user / accounts row for ${email} — did global-setup run?`);
    accountId = user.id;
  });

  // ---- helpers (service-role reads for diff-based assertions) -------------------------------
  // Diff-based assertions avoid needing the post's db id from the DOM (the .cal-post tile carries
  // no data-id): we snapshot DB state, drive the UI, then poll for the specific delta we expect.

  async function approvedIds(): Promise<Set<string>> {
    const { data, error } = await adminDb()
      .from("posts")
      .select("id")
      .eq("account_id", accountId)
      .eq("approval_state", "approved");
    if (error) throw error;
    return new Set((data ?? []).map((r) => r.id));
  }

  async function filmedScriptIds(): Promise<Set<string>> {
    const { data, error } = await adminDb()
      .from("founder_scripts")
      .select("id")
      .eq("account_id", accountId)
      .eq("filmed", true);
    if (error) throw error;
    return new Set((data ?? []).map((r) => r.id));
  }

  async function contentSnapshot(): Promise<Map<string, string>> {
    const { data, error } = await adminDb().from("posts").select("id, content").eq("account_id", accountId);
    if (error) throw error;
    return new Map((data ?? []).map((r) => [r.id, JSON.stringify(r.content)]));
  }

  // ---- 1. generate: onboarding-generate adds posts to the test user's account ---------------
  test("generate lands new posts on the account", async ({ page }) => {
    test.setTimeout(180_000); // live generation streams from the model — give it room

    const before = await countPosts(accountId);

    await page.goto("/onboarding");
    await page.getByRole("button", { name: onboarding.getStartedBtn }).click(); // welcome → brand
    await page.getByRole("button", { name: onboarding.brandContinueBtn }).click(); // brand → audience
    await page.getByRole("button", { name: onboarding.audienceContinueBtn }).click(); // audience → channels
    await page.getByRole("button", { name: onboarding.channelsContinueBtn }).click(); // channels → connect
    await page.getByRole("button", { name: onboarding.generateBtn }).click(); // connect → loading

    // The loader streams generation, then router.push("/"). Wait for the dashboard, then poll the DB.
    await expect(page).toHaveURL(/\/$/, { timeout: 150_000 });

    await expect
      .poll(() => countPosts(accountId), { timeout: 120_000, message: "expected generate to add posts" })
      .toBeGreaterThan(before);
  });

  // ---- 2. chat-edit (step 6): applying a chat edit rewrites a post's content ----------------
  test("chat-edit apply changes a post's content", async ({ page }) => {
    const before = await contentSnapshot();

    await page.goto("/calendar");
    await calendar.firstPostTile(page).click(); // opens the drawer AND sets the opened post for chat
    await expect(drawer.panel(page)).toBeVisible();

    // Open the chat in single-post mode (a post is open → it proposes a live patch), ask for an edit.
    await page.getByRole("button", { name: chat.fabOpenAria }).click({ force: true });
    await expect(chat.panel(page)).toBeVisible();
    await page.getByLabel(chat.inputAria).fill(chat.postSuggestions[0]); // "Rewrite this warmer"
    await page.getByRole("button", { name: chat.sendAria }).click();

    // The proposed-edit card carries an Apply button; applying writes posts.content via applyPatch.
    const applyBtn = chat.changeCard(page).getByRole("button", { name: chat.applyBtn });
    await expect(applyBtn).toBeVisible({ timeout: 60_000 });
    await applyBtn.click();

    // Poll until some post's content diverges from the pre-edit snapshot (the opened post's row).
    await expect
      .poll(
        async () => {
          const after = await contentSnapshot();
          for (const [id, json] of after) {
            if (before.has(id) && before.get(id) !== json) return true;
          }
          return false;
        },
        { timeout: 60_000, message: "expected applied chat edit to change a post's content" },
      )
      .toBe(true);
  });

  // ---- 3. approve (step 7): Approve flips posts.approval_state → 'approved' -----------------
  test("approve flips a post's approval_state to approved", async ({ page }) => {
    const before = await approvedIds();

    await page.goto("/calendar");
    const tiles = calendar.postTiles(page);
    await expect(tiles.first()).toBeVisible();

    // Approve is the primary action for NON-video posts (video shows "Mark filmed"). Open tiles
    // until the drawer offers Approve, then click it.
    const count = await tiles.count();
    let approved = false;
    for (let i = 0; i < count; i += 1) {
      await tiles.nth(i).click();
      await expect(drawer.panel(page)).toBeVisible();
      const approveBtn = drawer.panel(page).getByRole("button", { name: drawer.approveBtn });
      if (await approveBtn.isVisible().catch(() => false)) {
        await approveBtn.click();
        approved = true;
        break;
      }
      await page.keyboard.press("Escape"); // close + try the next tile
      await expect(drawer.panel(page)).toBeHidden();
    }
    expect(approved, "expected at least one non-video post to offer Approve").toBe(true);

    // The newly-approved post is whichever id is in the after-set but not the before-set.
    await expect
      .poll(
        async () => {
          const after = await approvedIds();
          return [...after].some((id) => !before.has(id));
        },
        { timeout: 60_000, message: "expected Approve to set approval_state='approved'" },
      )
      .toBe(true);
  });

  // ---- 4. mark-filmed (step 5): Mark filmed flips founder_scripts.filmed → true -------------
  // `filmed` lives on founder_scripts (NOT posts) — see db.ts isScriptFilmedByPost. The Scripts
  // surface is unambiguously video, so we drive Mark filmed there.
  test("mark filmed flips founder_scripts.filmed to true", async ({ page }) => {
    const before = await filmedScriptIds();

    await page.goto("/scripts");
    const cards = scripts.cards(page);
    await expect(cards.first()).toBeVisible();

    // Click the first card's "Mark filmed" (some cards may already be filmed and omit the button).
    const cardCount = await cards.count();
    let clicked = false;
    for (let i = 0; i < cardCount; i += 1) {
      const btn = cards.nth(i).getByRole("button", { name: scripts.markFilmedBtn });
      if (await btn.isVisible().catch(() => false)) {
        await btn.click();
        clicked = true;
        break;
      }
    }
    expect(clicked, "expected an unfilmed script offering Mark filmed").toBe(true);

    await expect
      .poll(
        async () => {
          const after = await filmedScriptIds();
          return [...after].some((id) => !before.has(id));
        },
        { timeout: 60_000, message: "expected Mark filmed to set founder_scripts.filmed=true" },
      )
      .toBe(true);
  });
});
